'use strict';
/* engine.delivery.js — the §19-20 single-bundle delivery archive.
 * Seeds a realistic .sovereign/ store + a generated repo, assembles the
 * bundle, and asserts the manifest + entry set + continuation state. */
const fs = require('fs');
const path = require('path');
const vm = require('vm');

function makeWin() {
  const win = { console, setTimeout, clearTimeout };
  win.window = win;
  win.localStorage = { getItem: () => null, setItem: () => {}, removeItem: () => {} };
  const data = {}, sov = {};
  win.Engine = {
    FS: {
      _data: data,
      isFile: (p) => !!data[p], exists: (p) => p in data,
      read: (p) => (data[p] ? data[p].content : null),
      write: (p, c) => { data[p] = { type: 'file', content: String(c) }; },
      remove: (p) => { Object.keys(data).forEach((k) => { if (k === p || k.startsWith(p + '/')) delete data[k]; }); }
    },
    Sovereign: {
      read: (p) => (sov[p] != null ? (/\.json$/.test(p) ? JSON.parse(sov[p]) : sov[p]) : null),
      write: (p, d) => { sov[p] = typeof d === 'string' ? d : JSON.stringify(d); },
      list: () => Object.keys(sov)
    }
  };
  vm.createContext(win);
  vm.runInContext(fs.readFileSync(path.join(__dirname, '..', 'dist', 'engine.delivery.js'), 'utf8'), win, { filename: 'engine.delivery.js' });
  return win;
}

module.exports = async function (t) {
  const win = makeWin();
  const D = win.Engine.Delivery;
  const Sov = win.Engine.Sovereign;
  const FS = win.Engine.FS;

  // ---- seed a verified run ----
  Sov.write('product-contract.json', { name: 'taskboard', type: 'web-app', requirements: [{ statement: 'CRUD tasks', priority: 'mandatory' }] });
  Sov.write('evidence-ledger.json', { claims: [{ id: 'C1', evidence: 'execution-evidence.json', confidence: 'high' }] });
  Sov.write('definition-of-done.json', { pass: true, criteria: { implementationExists: true, buildSucceeds: true, testsSucceed: true, accessibilityPass: true, performanceHealthy: true }, failing: [] });
  Sov.write('execution-evidence.json', { ok: true, summary: 'npm test 42/42, build ok' });
  Sov.write('a11y-findings.json', { score: 98, byImpact: {} });
  Sov.write('perf-findings.json', { present: true, p50: 3, p95: 21, p99: 55, errors: 0, leak: false });
  Sov.write('release-certificate.md', '# SOVEREIGN VERIFIED\n\ntaskboard — all 14 gates passed.\n');
  Sov.write('ultramode-report.md', '# Ultra Mode run — r1\n\nState: VERIFIED\n');
  Sov.write('ultramode-run.json', JSON.stringify({ runId: 'r1', state: 'VERIFIED', result: 'VERIFIED', contract: { name: 'taskboard', type: 'web-app' } }));
  Sov.write('ultramode-plan.json', JSON.stringify({ steps: [{ kind: 'scaffold' }, { kind: 'deploy-iac' }] }));
  FS.write('/README.md', '# taskboard\n\nGenerated by **CodeSovereign**\n\n## Documentation\n');
  FS.write('/docs/API.md', '# taskboard — HTTP API\n\n## Entities\n');
  FS.write('/docs/DATABASE.md', '# taskboard — database\n');
  FS.write('/docs/DEPLOYMENT.md', '# taskboard — deployment\n');
  FS.write('/docs/TROUBLESHOOTING.md', '# taskboard — troubleshooting\n');

  // ---- manifest ----
  const m = D.manifest();
  t.equal('manifest: product name from the contract', m.product, 'taskboard');
  t.equal('manifest: verdict is VERIFIED', m.verdict, 'VERIFIED');
  t.equal('manifest: DoD summarised as pass', m.definitionOfDone.pass, true);
  t.equal('manifest: DoD total counted', m.definitionOfDone.total, 5);
  t.ok('manifest: performance folded in', m.performance && m.performance.p95 === 21);
  t.equal('manifest: certificate flagged present', m.certificate, true);
  t.equal('manifest: continuation flagged present', m.continuationIncluded, true);
  t.equal('manifest: resume state captured', m.resumeState, 'VERIFIED');
  t.ok('manifest: content hash is an 8-hex digest', /^[0-9a-f]{8}$/.test(m.contentHash));
  t.ok('manifest: per-file hashes recorded', m.files.length > 8 && m.files.every((f) => /^[0-9a-f]{8}$/.test(f.sha)));

  // ---- assemble ----
  const a = D.assemble();
  const names = a.entries.map((e) => e.name);
  t.ok('assemble: MANIFEST.json + README.md first', names[0] === 'MANIFEST.json' && names[1] === 'README.md');
  t.ok('assemble: certificate + report at top level', names.includes('release-certificate.md') && names.includes('ultramode-report.md'));
  t.ok('assemble: evidence namespaced under evidence/', names.includes('evidence/definition-of-done.json') && names.includes('evidence/evidence-ledger.json'));
  t.ok('assemble: continuation state included', names.includes('continuation/ultramode-run.json') && names.includes('continuation/ultramode-plan.json'));
  t.ok('assemble: docs included', names.includes('docs/API.md') && names.includes('docs/TROUBLESHOOTING.md'));
  t.ok('assemble: README explains the verdict', /Verdict — \*\*VERIFIED\*\*/.test(a.entries[1].data));

  // ---- write into FS ----
  const w = D.write();
  t.ok('write: lays the bundle under /delivery/', w.wrote.includes('/delivery/MANIFEST.json') && w.wrote.includes('/delivery/evidence/definition-of-done.json'));
  t.ok('write: records .sovereign/delivery-manifest.json', D.load() && D.load().verdict === 'VERIFIED');
  t.equal('write: MANIFEST.json in FS parses', JSON.parse(FS.read('/delivery/MANIFEST.json')).product, 'taskboard');

  // ---- stale bundle is cleared on rewrite ----
  FS.write('/delivery/evidence/stale-old.json', '{}');
  D.write();
  t.equal('write: a stale bundle file is removed on rewrite', FS.read('/delivery/evidence/stale-old.json'), null);

  // ---- partial / incomplete run ----
  const win2 = makeWin();
  win2.Engine.Sovereign.write('definition-of-done.json', { pass: false, criteria: { implementationExists: true, testsSucceed: false }, failing: ['testsSucceed'] });
  const m2 = win2.Engine.Delivery.manifest();
  t.equal('manifest: no cert + failing DoD -> INCOMPLETE', m2.verdict, 'INCOMPLETE');
  t.equal('manifest: failing criteria listed', m2.definitionOfDone.failing[0], 'testsSucceed');
};
